apiVersion: v1
kind: Secret
metadata:
  name: {{ include "materialis.mysqlName" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "materialis.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | quote }}
