apiVersion: v1
kind: Service
metadata:
  name: {{ include "materialis.appName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "materialis.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "materialis.appName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
